### ISSUE TITLE
Add the pyhton programs 

### ISSUE THREAD

**Issue by Preetpalkaur3701** [Preetpalkaur3701/Python#1]
Add the python programs.

**Comment by adityagupta-16** [comment]
@Preetpalkaur3701  which program you need  . Justify  your issue  and Do assign  me .

**Comment by Preetpalkaur3701** [comment]
Any program using OOPs.

**Comment by adityagupta-16** [comment]
hacktoberfest-accepted  label as it is (using hyphen) then only  PR gets
accepted by Team hacktoberfest.
