### ISSUE TITLE
Label Repo as Hacktoberfest

### ISSUE THREAD

**Issue by Nitsujed** [Preetpalkaur3701/Python#29]
Hey, just curious if you could label this repo as "hacktoberfest". It looks like you are labeling all the issues as such and accepting the PRs with the right label, but I think it would work nicer if you label the whole repo as hacktoberfest.

Just a suggestion. Thanks, hope your project goes well.

**Comment by Preetpalkaur3701** [comment]
I set the topic of this repo to hacktoberfest. All set now! :)
