### ISSUE TITLE
shortest path in directed acyclic graph O(n) solution using iterative topological sort

### ISSUE THREAD

**Issue by mohinesh9999** [Preetpalkaur3701/Python#36]
I think this problem deserve this repo.
I will be happy if you assign it to me i think i can solve it @Preetpalkaur3701 
it will be nice if you add hacktober tag.

**Comment by Preetpalkaur3701** [comment]
Assigned!

**Comment by mohinesh9999** [comment]
added pr @Preetpalkaur3701 #49
